### PR TITLE
Number Keyboard Fixes

### PR DESCRIPTION
**Pull request by johnthepink**
Fixes NewSpring/my.newspring.cc#90

### CODE REVIEW

**Comment by johnthepink** [comment]
Fixes NewSpring/my.newspring.cc#85

**Comment by johnthepink** [comment]
Fixes NewSpring/my.newspring.cc#82

**Comment by johnthepink** [comment]
@jbaxleyiii this should be ready now

**Comment by jbaxleyiii** [comment]
keyboard

**Pull request merged**
