### PR TITLE
Prevent scrolling when a modal is open.

### PR DESCRIPTION
**Pull request by johnthepink**
Fixes NewSpring/my.newspring.cc#102

### CODE REVIEW

**Comment by jbaxleyiii** [comment]
@johnthepink where does the class on the html get removed?

**Comment by johnthepink** [comment]
@jbaxleyiii haha. fixed because not awake yet.

**Comment by jbaxleyiii** [comment]
@johnthepink haha I get it sleep

**Comment by johnthepink** [comment]
@jbaxleyiii i did actually push a fix though. I just amended the commit:

https://github.com/NewSpring/apollos-core/pull/90/files#diff-bf5774ad86b55c9e357f5ebc80929b04R85

But, now I'm wondering if we should just do this on mobile, because on desktop we get this pretty non-scrollbar:

screenshot 2015-08-02 09 19 24

**Comment by jbaxleyiii** [comment]
@johnthepink that is really gross. I wonder what element needs overflow:hidden on it when active?

**Comment by johnthepink** [comment]
@jbaxleyiii i'm gonna play with it some more.

**Comment by jbaxleyiii** [comment]
@johnthepink 
play

**Comment by johnthepink** [comment]
@jbaxleyiii turns out, that is just what Safari do, with or without the `modal--opened` change. Firefox is cool with it, and so is Chrome. So I think we can merge this, and I will open a separate issue for the Safari fix.

**Comment by jbaxleyiii** [comment]
@johnthepink sounds great. Browsers man...

**Pull request merged**
