### PR TITLE
[WIP] Abstract forms

### PR DESCRIPTION
**Pull request by johnthepink**
@jbaxleyiii @benwiley here was today's attempt to abstract the form to core. I think it can be done. The new `Apollos.Forms.Form` component handles most of the lifting now.

Couple things/issues I notice:

  - I got rid of the component files for each form, since they weren't doing anything. But, this messed up the children relationship. I guess we could register the components and that's it?
  - Because of the children problem, the validations are currently broken, but that could be fixed.
  - I tried to incorporate Apollos.Controls.Toggle in to the form component, but I didn't find a good way to pass the toggle state reactive var through everything.

I do like the idea of just having one form component.

### CODE REVIEW

**Comment by johnthepink** [comment]
[WIP] means Work In Progress btw

**Comment by jbaxleyiii** [comment]
@johnthepink this is great! Let me show you the card work I've been doing recently. I think it could work great for this! Awesome!

**Comment by jbaxleyiii** [comment]
@johnthepink take a look at #41 and see if it will help with some of the issues above.

**Comment by johnthepink** [comment]
Closing in favor of #43

**Pull request closed without merging**
