### PR TITLE
Fix for generating form ids

### PR DESCRIPTION
**Pull request by johnthepink**
Fixes NewSpring/my.newspring.cc#104

### CODE REVIEW

**Comment by jbaxleyiii** [comment]
@johnthepink is that the right issue?

**Comment by johnthepink** [comment]
@jbaxleyiii yea it is. It doesn't make the fix, but the form ID is used in the fix.

**Comment by jbaxleyiii** [comment]
@johnthepink gotcha! Thanks for the clarity! Also, pokemon gifs all day today (sorry not sorry)

clarity!

**Comment by johnthepink** [comment]
@jbaxleyiii oh I'm not sorry

**Comment by jbaxleyiii** [comment]
@johnthepink you get me

love

**Pull request merged**
